### ISSUE TITLE
streamingServerUrl

### ISSUE THREAD

**Issue by ihavenoidea14** [MaxCam/BGPlay#3]
Great project! Really enjoyed getting this stood up for my networking team. The team is now asking that I set up the real-time updates using websockets. I haven't been able to find any documentation regarding which address/location to use for this parameter when initializing the widget. Any help/guidance would be greatly appreciated.

**Comment by massimocandela** [comment]
Hi, it depends on your real-time BGP data provider. The Isolario one is ws://isolario.it/my_subnet_reachability. There was one for CAIDA that no longer works and there will be one for RIPE RIS soon.
